name: iOS CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "ios-app-development" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Xcode version
      run: xcodebuild -version